# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-housing-ageron',
                'doc_host': 'https://BriceChivu.github.io',
                'git_url': 'https://github.com/BriceChivu/test-housing-ageron',
                'lib_path': 'test_housing_ageron'},
  'syms': {'test_housing_ageron.core': {'test_housing_ageron.core.foo': ('core.html#foo', 'test_housing_ageron/core.py')}}}
